import { black, mainPink, white } from "@/src/styles/colors";
import { StyleSheet } from "react-native";

export default StyleSheet.create({
  card: {
    flexDirection: "row",
    backgroundColor: white,
    borderRadius: 16,
    padding: 16,
    marginHorizontal: 16,
    marginBottom: 16,
  },
  posterContainer: {
    marginRight: 16,
    shadowColor: black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    borderRadius: 12,
  },
  poster: {
    width: 150,
    height: 220,
    borderRadius: 12,
  },
  placeholderPoster: {
    backgroundColor: "#e0e0e0",
    justifyContent: "center",
    alignItems: "center",
  },
  placeholderText: {
    color: "#999",
    fontSize: 12,
  },
  infoContainer: {
    flex: 1,
    justifyContent: "flex-start",
    paddingTop: 4,
  },
  title: {
    fontSize: 20,
    fontWeight: "bold",
    color: black,
    marginBottom: 8,
    lineHeight: 24,
  },
  genre: {
    fontSize: 14,
    color: "#666",
    marginBottom: 16,
    fontWeight: 500,
  },
  dateContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: mainPink,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    alignSelf: "flex-start",
    marginBottom: 12,
  },
  dateIcon: {
    fontSize: 14,
    marginRight: 6,
  },
  dateText: {
    color: white,
    fontSize: 13,
    fontWeight: 600,
  },
  trailerButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFE0E8",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    alignSelf: "flex-start",
  },
  trailerIcon: {
    color: mainPink,
    fontSize: 12,
    marginRight: 6,
  },
  trailerText: {
    color: mainPink,
    fontSize: 13,
    fontWeight: "600",
  },
  fullScreenModal: {
    flex: 1,
    backgroundColor: "#000",
    justifyContent: "center",
    alignItems: "center",
  },
  closeButton: {
    position: "absolute",
    top: 50,
    right: 20,
    zIndex: 10,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#fff",
  },
  closeButtonText: {
    color: "#fff",
    fontSize: 24,
    fontWeight: "bold",
  },
  centeredContent: {
    width: "100%",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  trailerTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: white,
    marginBottom: 20,
    textAlign: "center",
  },
  playerContainer: {
    width: "100%",
    aspectRatio: 16 / 9,
    backgroundColor: "#000",
  },
});